version: "2"
services:
  postgres:
    image: registry.centos.org/centos/postgresql-94-centos7:latest
    network_mode: bridge
    ports:
     - "5432:5432"
    hostname: coreapi-postgres
    environment:
      POSTGRESQL_USER: coreapi
      POSTGRESQL_PASSWORD: coreapipostgres
      POSTGRESQL_DATABASE: coreapi
    container_name: coreapi-postgres