version: "2"
services:
  postgres:
    image: registry.centos.org/centos/postgresql-96-centos7:latest
    network_mode: bridge
    ports:
     - "5432:5432"
    hostname: coreapi-postgres
    environment:
      POSTGRESQL_USER: coreapi
      POSTGRESQL_PASSWORD: coreapi
      POSTGRESQL_DATABASE: coreapi
    container_name: coreapi-postgres

  alembic_migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    network_mode: bridge
    restart: on-failure
    hostname: alembic_migrations
    links:
      - postgres
    container_name: alembic_migrations
    environment:
      POSTGRESQL_USER: coreapi
      POSTGRESQL_PASSWORD: coreapi
      POSTGRESQL_DATABASE: coreapi
      PGBOUNCER_SERVICE_HOST: coreapi-postgres
      PGBOUNCER_SERVICE_PORT: 5432

  f8a_ingestion:
    build: .
    network_mode: bridge
    ports:
     - "5000:5000"
    hostname: f8a_ingestion
    environment:
      POSTGRESQL_USER: coreapi
      POSTGRESQL_PASSWORD: coreapi
      POSTGRESQL_DATABASE: coreapi
      PGBOUNCER_SERVICE_HOST: coreapi-postgres
      PGBOUNCER_SERVICE_PORT: 5432
    links:
      - postgres
    container_name: f8a_ingestion
