swagger: "2.0"
info:
  title: API for Fabric8 Analytics Ingestion
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  auth_token:
    type: "apiKey"
    name: "auth-token"
    in: "header"

paths:
  /liveness:
    get:
      tags: [Service settings]
      operationId: rest_api.liveness
      summary: Get job service liveness
      responses:
        200:
          description: Service is alive
  /readiness:
    get:
      tags: [Service settings]
      operationId: rest_api.readiness
      summary: Get job service readiness
      responses:
        200:
          description: Service is ready