swagger: "2.0"
info:
  title: API for Fabric8 Analytics Ingestion
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
paths:
  /liveness:
    get:
      tags: [Service settings]
      operationId: rest_api.liveness
      summary: Get job service liveness
      responses:
        200:
          description: Service is alive
  /readiness:
    get:
      tags: [Service settings]
      operationId: rest_api.readiness
      summary: Get job service readiness
      responses:
        200:
          description: Service is ready
  /ingest:
    post:
      tags: [Ingestion]
      operationId: rest_api.ingest
      summary: Ingests data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ecosystem_name
          in: body
          required: true
          description: JSON describing SQL query
          schema:
            $ref: "#/definitions/Ingestion" 
      responses:
        200:
          description: Data ingestion is successful
        400:
          description: Error in data ingestion

definitions:
  Ingestion:
    title: Ecosystem Details
    description: Ecosystem Details
    properties:
      ecosystem:
        type: string
      url:
        type: string
      backend:
        type: string
      package:
        $ref: "#/definitions/package"
      version: 
        $ref: "#/definitions/version"
  package:
    additionalProperties:
      type: string  
  version:
    additionalProperties:
      type: string