apiVersion: v1
kind: Template
labels:
  template: f8a-analytics-ingestion
metadata:
  name: f8a-analytics-ingestion
  annotations:
    description: f8a-analytics-ingestion
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-analytics-ingestion
    name: f8a-analytics-ingestion
  spec:
    replicas: "${{REPLICAS}}"
    selector:
      service: f8a-analytics-ingestion
    strategy:
      type: Rolling
      rollingParams:
        pre:
          failurePolicy: Retry
          execNewPod:
            containerName: f8a-analytics-ingestion
            command: ["/ingestion-pre-hook.sh"]
    template:
      metadata:
        labels:
          service: f8a-analytics-ingestion
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
          - name: PGBOUNCER_SERVICE_HOST
            value: coreapi-postgres
          - name: PGBOUNCER_SERVICE_PORT
            value: "5432"
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: INGESTION_API_SERVICE_PORT
            value: "5000"
          - name: INGESTION_API_SERVICE_TIMEOUT
            value: "60"
          - name: NUMBER_WORKER_PROCESS
            value: "4"
          - name: CLASS_TYPE
            value: "sync"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-analytics-ingestion
          ports:
          - containerPort: ${{INGESTION_API_SERVICE_PORT}}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            tcpSocket:
              port: ${{INGESTION_API_SERVICE_PORT}}
          readinessProbe:
            tcpSocket:
              port: ${{INGESTION_API_SERVICE_PORT}}
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: f8a-analytics-ingestion
    name: f8a-analytics-ingestion
  spec:
    ports:
    - port: ${{INGESTION_API_SERVICE_PORT}}
      name: "${INGESTION_API_SERVICE_PORT}"
      targetPort: ${{INGESTION_API_SERVICE_PORT}}
      protocol: TCP
    selector:
      service: f8a-analytics-ingestion
- apiVersion: v1
  kind: Route
  metadata:
    name: f8a-analytics-ingestion
  spec:
    host: ${INGESTION_API_HOSTNAME}
    to:
      kind: Service
      name: f8a-analytics-ingestion

parameters:
- description: A hostname where the fabric8-analytics Ingestion API should be exposed (will be auto-generated if empty)
  displayName: fabric8-analytics Ingestion API hostname
  required: false
  name: INGESTION_API_HOSTNAME

- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "125m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "500m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "128Mi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "512Mi"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics/f8a-analytics-ingestion"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

- description: Port Number
  displayName: Port Number
  required: true
  name: INGESTION_API_SERVICE_PORT
  value: "5000"
